apiVersion: v1
kind: Pod
metadata:
 name: busybox2
spec:
 volumes:
 - name: demo
   configMap:
    name: sample-configmap
 containers:
 - image: busybox
   name: busybox
   command: ["/bin/sh"]
   args: ["-c", "sleep 500"]
   volumeMounts:
   - name: demo
     mountPath: /mounted_configmap_volume